### ISSUE TITLE
Incorrect conversion of small-caps

### ISSUE THREAD

**Issue by ryanditjia** [postcss/postcss-font-variant#14]
Hello, I believe there’s a mistake with the small-caps conversion:

```css
/* current */
h2 {
  font-feature-settings: "c2sc"; /* this is for caps to small caps */
  font-variant-caps: small-caps;
}

/* should be */
h2 {
  font-feature-settings: "smcp";
  font-variant-caps: small-caps;
}
```
