### ISSUE TITLE
Invalid output produced

### ISSUE THREAD

**Issue by unconfident** [postcss/postcss-font-variant#17]
Having `font-variant` set to `initial` before `font-feature-settings` property somehow corrupts produced output for `font-feature-settings`.

**Input:**

```css
.this-will-be-broken {
   font-variant: initial;
   font-feature-settings: normal;
}

.this-will-not {
  font-variant: normal;
  font-feature-settings: normal;
}
```

**Expected output**

Should match the input one to one

**Produced output:**

```css
.this-will-be-broken {
   font-variant: initial;
   font-feature-settings: normal, ;
}

.this-will-not {
  font-variant: normal;
  font-feature-settings: normal;
}
```

Observing this on version `4.0.1` but saw the same happen nearly a year ago, before `4.0.1` was released, so I guess at least `4.0.0` is affected as well.
